version: "3"
services:
  dev:
    build: ./dev_docker
    depends_on:
      - sql_server
    environment:
      - ERL_TOP=/otp
      - MSSQL_UID=sa
      - MSSQL_PWD=The_Password
      - ODBCINI=/odbc_ini/.odbc.ini
    volumes:
      - ./otp:/otp
      - ./dev_home:/odbc_ini

  sql_server:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=The_Password
    ports:
      - "1433:1433"
